apiVersion: v1
kind: PersistantVolume
metadata:
  name: mongopv
spec:
  capacity:
     storage: 5Gi    #specify how much storage you need
  accessModes:
    -ReadWriteOnce #r//w by a single node
    -ReadOnlyMany  
    -RWM -- #r/w by many nodes
    -ReadWriteOncePod #r/w by single pod only
  local: #place where we want the data to be mounted (EBS or local or anythimg else)
     path: /storage/data
  nodeAffinity:
    
  
